title: Blog
email: jack@jackdalton.org
description: >
  Here, I write about random tech subjects.
baseurl: "/blog"
url: "http://jackdalton.org"
#twitter_username: I never really liked Twitter.
github_username:  jackdalton
markdown: kramdown